### HISTFILE {{{
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

setopt histignorealldups
setopt histignorespace
setopt appendhistory
setopt sharehistory
### }}}


### OPTIONS
setopt nomatch
setopt autocd
setopt extendedglob
setopt printexitvalue
setopt transientrprompt

unsetopt beep
unsetopt notify

REPORTTIME=2
### }}}


### COMPLETION {{{
zstyle :compinstall filename '$HOME/.zshrc'
autoload -Uz compinit
compinit

zstyle ':completion:*' menu select=2
zstyle ':completion:*' verbose yes

setopt correct
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*:*:vim:*:*files' ignored-patterns '*.class'
### }}}


### COLORS {{{
# Set prompt
export TERM=xterm-256color
autoload -U colors
colors
PROMPT="%n@%{$fg_bold[blue]%}%m %{$fg_no_bold[cyan]%}%3~ %{$reset_color%}%# "

# Set ls colors
eval `dircolors /home/toffan/.ls_colors`
### }}}

### ALIASES {{{
mkdircd () {
    mkdir $1;
    cd $1;
}
todo () {
    markdown ~/todolist.md > /tmp/todo.html;
    firefox /tmp/todo.html;
}

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias pacman='pacman --color auto'

alias -g :g='| grep'
alias -g :l='| less'
alias -g :h='| head'
alias -g :t='| tail'
alias -g :w='| wc'

alias alert='notify-send --urgency=low'
alias ll='ls -lh --time-style=long-iso'
alias lll='ll -a'
alias fuck='sudo $(fc -ln -1)'
alias fucking='sudo'

alias mountdata='sudo mount /dev/sdb1 /media/data'
alias umountdata='sudo umount /media/data'
alias mountusb='sudo mount /dev/sdc1 /media/usb'
alias umountusb='sudo umount /media/usb'

alias javadoc='javadoc -encoding UTF-8 -docencoding UTF-8 -charset UTF-8'

alias -s pdf="evince "

alias azer='setxkbmap fr bepo'
alias bépo='setxkbmap fr'
### }}}


# Environment variables
export EDITOR=/usr/bin/vim
export CLASSPATH=.:/usr/share/java/junit.jar

# Autojump
[[ -s /etc/profile.d/autojump.sh ]] && source /etc/profile.d/autojump.sh

# Keybindings
bindkey -e
bindkey '^R' history-incremental-search-backward
bindkey '^[[3~' delete
